#!/bin/sh
echo -n "Enter country code (in CAPITAL LETTERS): "
read COUNTRY
curl -s "https://archlinux.org/mirrorlist/?country=$COUNTRY&amp;protocol=https&amp;use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 10 - | sudo tee /etc/pacman.d/mirrorlist
